apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: tokishorbankar/k8s-demo-app:v1.0
        ports:
        - containerPort: 3000
        env:
        - name: USER_NAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: USER_NAME
        - name: USER_PWD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: USER_PWD
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: MONGO_URL
